import graphviz

def nfa6():
    f = graphviz.Digraph('finite_state_machine', filename='fsm.gv')
    f.attr(rankdir='LR', size='8,5')
    f.attr('node', shape='circle')
    f.edge('a', 'a', label='0,1')
    f.edge('a', 'b', label='1')
    f.edge('b', 'c', label='0')
    f.edge('c', 'd', label='1')
    f.edge('d', 'e', label='1')
    f.edge('e', 'f', label='0')
    f.edge('f', 'g', label='1')
    f.view()


def dfa_from_nfa6():
    f = graphviz.Digraph('finite_state_machine', filename='fsm.gv')
    f.attr(rankdir='LR', size='8,5')
    f.attr('node', shape='doublecircle')
    f.node('{a,b,g}')
    f.attr('node', shape='point')
    f.node('qi')
    f.attr('node', shape='circle')
    f.edge('qi', '{a}')
    f.edge('{a}', '{a}', label='0')
    f.edge('{a}', '{a,b}', label='1')
    f.edge('{a,b}', '{a,c}', label='0')
    f.edge('{a,b}', '{a,b}', label='1')
    f.edge('{a,c}', '{a}', label='0')
    f.edge('{a,c}', '{a,d,b}', label='1')
    f.edge('{a,d,b}', '{a,c}', label='0')
    f.edge('{a,d,b}', '{a,e}', label='1')
    f.edge('{a,e}', '{a,f}', label='0')
    f.edge('{a,e}', '{a,b}', label='1')
    f.edge('{a,f}', '{a}', label='0')
    f.edge('{a,f}', '{a,b,g}', label='1')
    f.edge('{a,b,g}', '{a,c}', label='0')
    f.edge('{a,b,g}', '{a,b}', label='1')
    f.view()